[package]
name = "tensorflow-inference"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Inferencing using pre-built Tensorflow models."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.14"
image = "0.23.14"
pinecone = "0.2.3"
tract-tensorflow = "0.14.2"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3

