[package]
name = "number-stream-accumulation"
version = "0.1.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "Computes the sum of two values and an initial value if there is no previous result. Otherwise, computes the sum of two values and the previous result." 

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pinecone = "0.2"
serde = "1.0"

[profile.release]
codegen-units = 1
lto = true
opt-level = 3
