[package]
name = "oblivious-routing"
version = "0.3.0"
authors = ["The Veracruz Development Team"]
edition = "2018"
description = "A simple test program, privacy-preserving routing in a graph (using the A-star algorithm), for demonstrating how to deploy computations on Veracruz."

[features]
std = []

[dependencies]
anyhow = "1.0.41"
pinecone = "0.2"
pathfinding = "2.1.5"
serde = { version = "1.0.97", features = ["derive"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
